version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./src:/var/www/
      - ./sites-enabled/default:/etc/nginx/conf.d/default.conf
    environment:
     - NGINX_PORT=80
    ports:
      - "80:80"
  api:
    build: ./api/
    command: npm start
    ports:
      - "3000:3000"
